### ISSUE TITLE
How is openwindow supposed to work?

### ISSUE THREAD

**Issue by MrWGT** [SeydX/homebridge-fritz-platform#193]
I added active and openwindow to my thermostats:

`{
                    "active": true,
                    "name": "Heizung Leana",
                    "ain": "099950409035",
                    "window": true,
                    "battery": true,
                    "accType": "thermostat",
                    "openWindow": true,
                    "temperature": true
                },
                {
                    "active": true,
                    "name": "Fenstererkennung KiZi",
                    "ain": "099950409035",
                    "battery": true,
                    "accType": "window"
                },
                {
                    "active": true,
                    "name": "Heizung WZ",
                    "ain": "099950453543",
                    "window": true,
                    "battery": true,
                    "accType": "thermostat",
                    "openWindow": true,
                    "temperature": true
                },
                {
                    "active": true,
                    "name": "Fenstererkennung WZ",
                    "ain": "099950453543",
                    "battery": true,
                    "accType": "window"
                }`

But log of hoobs shows:
`[FritzPlatform] Heizung Leana Open Window (smarthome-window-switch): Can not find device with AIN: 099950409035
[FritzPlatform] Heizung WZ Open Window (smarthome-window-switch): Can not find device with AIN: 099950453543`

What is missing in my config? Thanks, Gerd

**Comment by MrWGT** [comment]
Switches are shown in home and toggling on, press ok on thermostat, shows "window open". Switching off, press ok, and window closed detected. So it looks like it works but the above log messages are still there.

**Comment by SeydX** [comment]
Do the messages keep coming? Or did it just come once?

**Comment by MrWGT** [comment]
Just once after start

**Comment by SeydX** [comment]
@MrWGT 

Can u test v6.0.2-beta.0 pls? 
(You can safely update from test back to stable from within the UI.)

``sudo npm i -g homebridge-fritz-platform@beta``

**Comment by SeydX** [comment]
Fixed in v6.2

**Comment by MrWGT** [comment]
Sorry... Had a lot of work today. Installed 6.0.4 over hoobs but problem still exists after start of service (just once):
22.6.2021, 17:57:57 [FritzPlatform] Heizung WZ Open Window (smarthome-window-switch): Can not find device with AIN: 099950453543
22.6.2021, 17:57:57 [FritzPlatform] Heizung Leana Open Window (smarthome-window-switch): Can not find device with AIN: 099950409035

Using Fritz Platform
6.0.4 veröffentlicht 6/22/2021 • 6 hours ago

**Comment by SeydX** [comment]
> Sorry... Had a lot of work today. Installed 6.0.4 over hoobs but problem still exists after start of service (just once):
> 22.6.2021, 17:57:57 [FritzPlatform] Heizung WZ Open Window (smarthome-window-switch): Can not find device with AIN: 099950453543
> 22.6.2021, 17:57:57 [FritzPlatform] Heizung Leana Open Window (smarthome-window-switch): Can not find device with AIN: 099950409035
> 
> Using Fritz Platform
> 6.0.4 veröffentlicht 6/22/2021 • 6 hours ago

But its working normally? only the message at start is the problem?

**Comment by MrWGT** [comment]
Yes, working normal. Just once at start for each thermostat. Update to 6.0.5 but it's the same:

[23.06.21, 07:31] [FritzPlatform] Heizung WZ Open Window (smarthome-window-switch): Can not find device with AIN: 099950453543

[23.06.21, 07:31] [FritzPlatform] Heizung Leana Open Window (smarthome-window-switch): Can not find device with AIN: 099950409035
