### ISSUE TITLE
A thermostat group shows 0°C as current temperature

### ISSUE THREAD

**Issue by Gummibando** [SeydX/homebridge-fritz-platform#219]
A thermostat group shows 0°C as current temperature, while the individual thermostats contained in the group show the correct temperature.

Please see attached screenshot.

Homebridge 1.3.4 / homebridge-fritz-platform v6.0.14

![Fritz Thermostat Group](https://user-images.githubusercontent.com/34392542/126838437-6bb6c094-3bee-4361-9a2d-108b5a332d8c.png)

**Comment by SeydX** [comment]
I pushed a new beta version, can u check it pls and confirm if the beta fix the issue

`sudo npm i -g homebridge-fritz-platform@beta`

Dont worry, u can always jump back to official version without any issues with following command:

`sudo npm i -g homebridge-fritz-platform@latest`

**Comment by SeydX** [comment]
fixed in v6.0.15

**Comment by jensJeb** [comment]
Unfortunately the bug still appears for me even after updating to v6.0.15.

Here is my debug log output (censored AIN):

[19/09/2021, 17:30:35] [FritzPlatform] [DEBUG] Wohnzimmer (smarthome-thermostat): {"name":"Wohnzimmer","id":"900","ain":"xyz","online":1,"bitmask":"4160","busy":0,"associated":[{"name":"Wohnzimmer links","id":"16","ain":"xyz","online":1,"bitmask":"320","busy":0,"battery":{"value":60,"low":0},"alert":false,"temperature":{"value":23.5,"offset":0},"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":false,"thermostat":{"current":22,"target":21,"windowOpen":0},"light":false},{"name":"Wohnzimmer rechts","id":"17","ain":"xyz","online":1,"bitmask":"320","busy":0,"battery":{"value":70,"low":0},"alert":false,"temperature":{"value":23.5,"offset":0},"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":false,"thermostat":{"current":22.5,"target":21,"windowOpen":0},"light":false}],"battery":{"value":65,"low":0},"alert":false,"temperature":{"value":23.5,"offset":0},"humidity":{"value":null},"powermeter":false,"switch":false,"button":false,"blind":false,"thermostat":{"current":0,"target":21,"windowOpen":0},"light":false}

I use two FritzDECT301 in a group named "Wohnzimmer" with a FritzDECT440 switch configured as external temperature sensor.

**Comment by Gummibando** [comment]
Sorry for replying late, was not in the last few days.

Skipped beta and installed 6.0.15.
Same here, still 0°C for thermostat group.

Additionally, 6.0.15 update showed release notes for 6.0.14 (?).
After rollback to 6.0.14 and reinstall of 6.0.15 release notes were correct.

**Comment by poloflipp** [comment]
I have 6.0.16 and the bug still occurs. Can you please reopen it?

**Comment by poloflipp** [comment]
I can confirm that it’s working again with 6.0.19. Thank you!!!
